import Head from 'next/head';
import { useState } from 'react';
import Screen1 from '../components/Screen/Screen1';
import SmoothScroll from '../components/scroll/SmoothScroll';
import Layout from '../components/layout/Layout';
import background from '../assets/images/profile.png';
import Navigation from '../components/navigation/Navigation';
import Modal from '../components/modal/Modal';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <Modal />
      <SmoothScroll>
        <Layout>
          <Screen1 
            title={'Консультация со мной -'}
            titleOne={'своевременный ответ'} 
            titleTwo={'для получение виз'}
            content={'Консультирование, предложение вариантов в конкретном случае, постоянная обратная связь'}
            image={background}
          />
          <div style={{ height: '100vh' }}></div>
        </Layout>
      </SmoothScroll>
    </div>
  )
}
