import Head from 'next/head'
import Image from 'next/image';
import Navigation from '../components/navigation/Navigation';
import Screen1 from '../components/Screen/Screen1';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navigation />
        <Screen1 />
        <div style={{ height: '100vh' }}></div>
      </div>
    </div>
  )
}
