import Head from 'next/head';
import Screen1 from '../components/Screen/Screen1';
import SmoothScroll from '../components/scroll/SmoothScroll';
import Layout from '../components/layout/Layout';
import background from '../assets/images/profile.png';
import Navigation from '../components/navigation/Navigation';
import Modal from '../components/modal/Modal';
import Main from '../components/ui/blockBg/Main';
import TitleBlock from '../components/ui/titleBlock/Titleblock';
import Margin from '../components/ui/margin/Margin';
import { showNavigation } from '../store/slice/NavigationSlice';


//Api
import ServicesBlock from '../components/services/ServicesBlock';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Modal />
      {/* <SmoothScroll> */}
        <Layout>
          <Screen1 
            title={'Консультация со мной -'}
            titleOne={'своевременный ответ'} 
            titleTwo={'для получение виз'}
            content={'Консультирование, предложение вариантов в конкретном случае, постоянная обратная связь'}
            image={background}
          />
            <Main >
              <TitleBlock title={'Услуги'} />
              <Margin />
              <ServicesBlock />
            </Main>
          <div  style={{ height: '100vh' }}></div>
        </Layout>
      {/* </SmoothScroll> */}
    </div>
  )
}
